[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "crypto"
version = "1.0.0"
description = "Discord bot for crypto"
authors = ["XDA <hm.thuan91@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.12.13"
ccxt = "^4.5.44"
pandas = "^2.2.0"
websocket-client = "^1.9.0"
requests = "^2.32.5"
discord-py = "^2.7.1"
matplotlib = "^3.10.8"
seaborn = "^0.13.2"
aiohttp = "^3.13.3"
python-dotenv = "^1.2.2"
numpy = ">=1.24,<3.0.0"
pandas-ta = "^0.4.71b0"
numba = "0.61.2"

[tool.poetry.group.dev.dependencies]
black = "^26.3.1"
flake8 = "^7.3.0"
pytest = "^9.0.2"
